[package]
name = "weaver-example"
version = "0.1.0"
edition = "2024"

[dependencies]
opentelemetry = "0.30.0"
opentelemetry_sdk = "0.30.0"
opentelemetry-stdout = "0.30.0"
opentelemetry-otlp = { version = "0.30.0", features = ["grpc-tonic"] }
tokio = { version = "1.0", features = ["full"] }
